---
- debug:
    msg: "Jestem acme"
- block:
    - name: generate acme priv key
      openssl_privatekey:
        path: /etc/ssl/ansible/priv.key
        size: 4096

    - name: create acme_account
      acme_account:
        account_key_src: /etc/ssl/ansible/priv.key
        state: present
        terms_agreed: true
        contact:
          - "mailto:{{ ssl.provider.account.email }}"
        acme_version: 2
        acme_directory: https://acme-v02.api.letsencrypt.org/directory


    - name: request certificate
      acme_certificate:
        account_key_src: /etc/ssl/ansible/priv.key
        csr: "/etc/ssl/ansible/{{ ssl.domains[0] }}/csr.pem"
        dest: "/etc/ssl/ansible/{{ ssl.domains[0] }}/cert.pem"
        fullchain_dest: "/etc/ssl/ansible/{{ ssl.domains[0] }}/fullchain.pem"
        challenge: dns-01
        acme_version: 2
        acme_directory: https://acme-v02.api.letsencrypt.org/directory
        remaining_days: 30
      register: _ssl_request

    - block:
        - name: setup records
          include_tasks: "provider_acme_{{ ssl.provider.challenge.provider | default('nsupdate') }}_setup.yml"

        - name: get certificate
          acme_certificate:
            account_key_src: /etc/ssl/ansible/priv.key
            csr: "/etc/ssl/ansible/{{ ssl.domains[0] }}/csr.pem"
            dest: "/etc/ssl/ansible/{{ ssl.domains[0] }}/cert.pem"
            fullchain_dest: "/etc/ssl/ansible/{{ ssl.domains[0] }}/fullchain.pem"
            challenge: dns-01
            acme_version: 2
            acme_directory: https://acme-v02.api.letsencrypt.org/directory
            remaining_days: 30
            data: "{{ _ssl_request }}"
          delegate_to: "{{ ssl.keyserver }}"

        - name: setup named records
          include_tasks: "provider_acme_{{ ssl.provider.challenge.provider | default('nsupdate') }}_clean.yml"

      delegate_to: "{{ ssl.provider.challenge.delegate | default(omit) }}"
      when: _ssl_request.changed

  become: true
  delegate_to: "{{ ssl.keyserver }}"
